i3wm_resource:
  config: "{{ i3wm_files }}"
  locker: "{{ i3wm_templates }}"
  volumectl: "{{ i3wm_templates }}"
  brightnessctl: "{{ i3wm_templates }}"
  statusbar: "{{ i3wm_files }}"

i3wm_dotdir:
  config: "~/.config/i3"
  utils: "~/.config/i3/utils"
  statusbar: "~/.config/i3status"

i3wm_packages:
  config:
    - name: dex
      distros: ['Archlinux']

  locker:
    - name: imagemagick
      distros: ['Archlinux']
    - name: xss-lock
      distros: ['Archlinux']
    - name: i3lock
      distros: ['Archlinux']

  volumectl:
    - name: libpulse
      distros: ['Archlinux']

  brightnessctl:
    - name: xorg-xbacklight
      distros: ['Archlinux']

  statusbar:
    - name: i3status
      distros: ['Archlinux']

i3wm_dotfiles:
  config:
    - name: configuration file
      kind: link
      should_backup: true
      src: "{{ i3wm_resource.config }}/config"
      dest: "{{ i3wm_dotdir.config }}/config"

  locker:
    - name: lock utility
      kind: template
      should_backup: true
      src: "{{ i3wm_resource.locker }}/lock.j2"
      dest: "{{ i3wm_dotdir.utils }}/lock"

  volumectl:
    - name: volume control utility
      kind: template
      should_backup: true
      src: "{{ i3wm_resource.volumectl }}/change_volume.j2"
      dest: "{{ i3wm_dotdir.utils }}/change_volume"

    - name: volume control utility
      kind: template
      should_backup: true
      src: "{{ i3wm_resource.volumectl }}/mute_volume.j2"
      dest: "{{ i3wm_dotdir.utils }}/mute_volume"

    - name: volume control utility
      kind: template
      should_backup: true
      src: "{{ i3wm_resource.volumectl }}/mute_mic.j2"
      dest: "{{ i3wm_dotdir.utils }}/mute_mic"

  brightnessctl:
    - name: brightness control utility
      kind: template
      should_backup: true
      src: "{{ i3wm_resource.brightnessctl }}/change_brightness.j2"
      dest: "{{ i3wm_dotdir.utils }}/change_brightness"

  statusbar:
    - name: brightness control utility
      kind: link
      should_backup: true
      src: "{{ i3wm_resource.statusbar }}/i3statusbar.conf"
      dest: "{{ i3wm_dotdir.statusbar }}/config"
