alacritty_resource:
  config_templates: "{{ alacritty_templates }}/config"
  terminal: "{{ alacritty_files }}/terminal"

alacritty_dotdir:
  config: "~/.config/alacritty"
  terminal: "{{ dphome }}/profile"

alacritty_dotfiles:
  - name: configuration file
    kind: template
    should_backup: true
    src: "{{ alacritty_resource.config_templates }}/alacritty.toml.j2"
    dest: "{{ alacritty_dotdir.config }}/alacritty.toml"
    
  - name: i3 sensible terminal
    kind: file
    should_backup: false
    src: "{{ alacritty_resource.terminal }}/terminal"
    dest: "{{ alacritty_dotdir.terminal }}/terminal"
