- name: "Install redshift packages applicable top any distro"
  tags: [packages, redshift-packages]
  ansible.builtin.package:
    state: latest
    name: "{{ item.name }}"
  become: true
  loop: "{{ red }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.distro == "any"
