- name: "ensure not overwriting existing {{ bashrc_dotfile.dest }}"
  tags: [setup, bash-setup]
  include_role:
    name: backup
  vars:
    target: "{{ bashrc_dotfile.dest }}"

- name: "symlink {{ bashrc_dotfile.dest }}"
  tags: [setup, bash-setup]
  file:
    src: "{{ bashrc_dotfile.src }}"
    dest: "{{ bashrc_dotfile.dest }}"
    state: link
    force: true
    follow: false

- name: "create {{ dotdir.bashrc }}"
  tags: [setup, bash-setup]
  file:
    path: "{{ dotdir.bashrc }}"
    state: directory

- name: "symlink bashrc dotfiles"
  tags: [setup, bash-setup]
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
    follow: false
  loop: "{{ bashrc_dotfiles }}"
  loop_control:
    label: "{{ item.dest }}"

- name: "set PS1PROFILE via {{ bashrc_ps1profile.dest }}"
  tags: [setup, bash-setup]
  copy:
    src: "{{ bashrc_ps1profile.src }}"
    dest: "{{ bashrc_ps1profile.dest }}"
    force: true
    follow: false
