- name: "Sub | Preserve existing {{ bash_bashrc.dest }}"
  tags: [setup, bash-setup]
  ansible.builtin.include_role:
    name: backup
  vars:
    backup_target: "{{ bash_bashrc.dest }}"

- name: "Sub | Copy bashrc template into dest: {{ bash_bashrc.dest }}"
  tags: [setup, bash-setup]
  ansible.builtin.template:
    src: "{{ bash_bashrc.src }}"
    dest: "{{ bash_bashrc.dest }}"
    force: true
    follow: false
    mode: '751'

- name: "Sub | Copy bashrc dotfiles"
  tags: [setup, bash-setup]
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
    follow: false
    mode: '751'
  loop: "{{ bash_bashrc_dotfiles }}"
  loop_control:
    label: "{{ item.dest }}"

- name: "Set PS1PROFILE via {{ bash_ps1profile.dest }}"
  tags: [setup, bash-setup]
  ansible.builtin.copy:
    src: "{{ bash_ps1profile.src }}"
    dest: "{{ bash_ps1profile.dest }}"
    force: true
    follow: false
    mode: '751'

- name: Install bash completion package
  tags: [packages, bash-packages]
  ansible.builtin.package:
    state: present
    name: bash-completion
  become: true
