- name: "ensure not overwriting existing {{ bashrc.dest }}"
  tags: [setup, bash-setup]
  include_role:
    name: backup
  vars:
    target: "{{ bashrc.dest }}"

- name: "symlink {{ bashrc.dest }}"
  tags: [setup, bash-setup]
  file:
    src: "{{ bashrc.src }}"
    dest: "{{ bashrc.dest }}"
    state: link
    force: true
    follow: false

- name: "create {{ dotdir.bashrc }}"
  tags: [setup, bash-setup]
  file:
    path: "{{ dotdir.bashrc }}"
    state: directory

- name: "symlink bashrc dotfiles"
  tags: [setup, bash-setup]
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
    follow: false
  loop: "{{ bashrc_dotfiles }}"
  loop_control:
    label: "{{ item.dest }}"

- name: "set PS1PROFILE via {{ ps1profile.dest }}"
  tags: [setup, bash-setup]
  copy:
    src: "{{ ps1profile.src }}"
    dest: "{{ ps1profile.dest }}"
    force: true
    follow: false

- name: install bash completion package
  tags: [packages, bash-packages]
  package:
    state: latest
    name: bash-completion
  become: true
