- name: "check for existing {{ dotdir }}"
  tags: [setup, bash-setup]
  stat: path="{{ dotdir }}"
  register: check_result

- name: "backup {{ dotdir }} if exists"
  tags: [setup, bash-setup]
  copy:
    src: "{{ dotdir }}"
    dest: "{{ dotdir }}.{{ bksuffix }}"
    follow: true
  when: check_result.stat.exists

- name: "create new {{ dotdir }}"
  tags: [setup, bash-setup]
  file:
    path: "{{ dotdir }}"
    state: directory
