- name: install bash completion package
  tags: packages
  package:
    state: latest
    name: bash-completion

- name: symlink bash configurations
  tags: setup
  file:
    src: "{{ configs_home }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
    follow: false
  loop: "{{ dotfiles }}"
  loop_control:
    label: "{{ item.dest }}"
