- name: install latest package
  tags: packages
  package:
    state: latest
    name: bash

- block:
  - import_tasks: main_dotfile.yml
  - import_tasks: dotdir.yml
  - import_tasks: bash_completion.yml
