- name: Install latest package
  tags: [packages, bash-packages]
  ansible.builtin.package:
    state: present
    name: bash
  become: true

- name: Ensure dotdirs exist
  tags: [setup, bash-setup]
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
    mode: '751'
  loop: "{{ bash_dotdir | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Setup
  block:
    - name: Profile
      ansible.builtin.import_tasks: profile.yml
    - name: Bashrc
      ansible.builtin.import_tasks: bashrc.yml
