- name: install bash
  tags: install-bash
  package:
    name: bash
    state: present
  become: true

- name: check for existing configs
  tags: backup-bash
  stat: path="{{ item.dest }}"
  loop: "{{ configs }}"
  loop_control:
    label: "{{ item.dest }}"
  register: configschecks

- name: backup existing configs
  tags: backup-bash
  copy:
    src: "{{ item.stat.path }}"
    dest: "{{ item.stat.path }}.{{ bksuffix }}"
    follow: true
  when: item.stat.exists
  loop: "{{ configschecks.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: symlink configs
  tags: config-bash
  file:
    src: "{{ role_path }}/data/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
    follow: false
  loop: "{{ configs }}"
