- name: install latest package
  tags: [packages, bash-packages]
  package:
    state: latest
    name: bash

- block:
  - import_tasks: main_dotfile.yml
  - import_tasks: profile_dotfiles.yml
  - import_tasks: bashrc_dotfiles.yml
