- name: Install latest package
  tags: [packages, bash-packages]
  ansible.builtin.package:
    state: present
    name: bash
  become: true

- name: Ensure dotdirs exist
  tags: [setup, bash-setup]
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
    mode: '751'
  loop: "{{ bash_dotdir | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: "Handle profile dotfiles"
  tags: [setup, bash-setup]
  ansible.builtin.include_role:
    name: dotfiles_handler
  vars:
    dotfiles_handler_target: "{{ bash_profile_dotfiles }}"

- name: "Handle bashrc dotfiles"
  tags: [setup, bash-setup]
  ansible.builtin.include_role:
    name: dotfiles_handler
  vars:
    dotfiles_handler_target: "{{ bash_bashrc_dotfiles }}"

- name: Install bash completion package
  tags: [packages, bash-packages]
  ansible.builtin.package:
    state: present
    name: bash-completion
  become: true
