- name: "ensure not overwriting existing {{ profile.dest }}"
  tags: [setup, bash-setup]
  include_role:
    name: backup
  vars:
    target: "{{ profile.dest }}"

- name: "symlink {{ profile.dest }}"
  tags: [setup, bash-setup]
  file:
    src: "{{ profile.src }}"
    dest: "{{ profile.dest }}"
    state: link
    force: true
    follow: false

- name: "create {{ dotdir.profile }}"
  tags: [setup, bash-setup]
  file:
    path: "{{ dotdir.profile }}"
    state: directory

- name: install profile dotfiles
  tags: [setup, bash-setup]
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
    follow: false
  loop: "{{ profile_dotfiles }}"
  loop_control:
    label: "{{ item.dest }}"
