- name: "Sub | Preserve existing {{ bash_profile.dest }}"
  tags: [setup, bash-setup]
  ansible.builtin.include_role:
    name: backup
  vars:
    backup_target: "{{ bash_profile.dest }}"

- name: "Sub | Copy profile templates into dest: {{ bash_profile.dest }}"
  tags: [setup, bash-setup]
  ansible.builtin.template:
    src: "{{ bash_profile.src }}"
    dest: "{{ bash_profile.dest }}"
    force: true
    follow: false
    mode: '751'

- name: "Sub | Copy profile dotfiles"
  tags: [setup, bash-setup]
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
    follow: false
    mode: '751'
  loop: "{{ bash_profile_dotfiles }}"
  loop_control:
    label: "{{ item.dest }}"
