- name: "Sub | Preserve selected profile configs"
  tags: [setup, bash-setup]
  ansible.builtin.include_role:
    name: backup
  vars:
    backup_target: "{{ item.dest }}"
  loop: "{{ bash_profile_dotfiles }}"
  loop_control:
    label: "{{ item.dest }}"
  when: item.should_backup

- name: "Sub | Copy profile templates"
  tags: [setup, bash-setup]
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
    follow: false
    mode: '751'
  loop: "{{ bash_profile_dotfiles }}"
  loop_control:
    label: "{{ item.dest }}"
  when: item.kind == "template"

- name: "Sub | Copy profile files"
  tags: [setup, bash-setup]
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
    follow: false
    mode: '751'
  loop: "{{ bash_profile_dotfiles }}"
  loop_control:
    label: "{{ item.dest }}"
  when: item.kind == "file"

- name: "Sub | Link profile files"
  tags: [setup, bash-setup]
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
    follow: false
  loop: "{{ bash_profile_dotfiles }}"
  loop_control:
    label: "{{ item.dest }}"
  when: item.kind == "link"
