- name: Set up the role resources facts
  tags: [setup, gammastep-setup]
  ansible.builtin.set_fact:
    gammastep_files: "{{ role_path }}/files"
    gammastep_templates: "{{ role_path }}/templates"

- name: Install latest package
  tags: [packages, gammastep-packages]
  ansible.builtin.package:
    state: present
    name: gammastep
  become: true

- name: Ensure dotdirs exist
  tags: [setup, gammastep-setup]
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
    mode: '751'
  loop: "{{ gammastep_dotdir | dict2items }}"
  loop_control:
    label: "{{ item.value }}"

- name: "Handle gammastep dotfiles"
  tags: [setup, gammastep-setup]
  ansible.builtin.import_role:
    name: dotfiles_handler
  vars:
    dotfiles_handler_target: "{{ gammastep_dotfiles }}"
