- hosts: local
  roles:
    - role: git
      tags: git

    - role: bash
      tags: bash

    - role: alacritty
      tags: alacritty

    - role: nvim
      tags: nvim

    - role: readline
      tags: [readline, never]

    - role: redshift
      tags: [redshift, never]

    - role: linux
      tags: linux

    - role: i3wm
      tags: i3wm

    - role: touchpad
      tags: [touchpad, never]
