role_files: "{{ role_path }}/files"

role_resource:
  profile: "{{ role_files }}/profile"
  bashrc: "{{ role_files }}/bashrc"

main_dotfile:
  src: "{{ role_resource }}/bash_profile"
  dest: ~/.bash_profile

dotdir:
  profile: "{{ dphome }}/profile"
  bashrc: "{{ dphome }}/bashrc"

profile_dotfiles:
  - path:
    src: "{{ role_resource.profile }}/path"
    dest: "{{ dotdir.profile }}/path"
  - pager:
    src: "{{ role_resource.profile }}/pager"
    dest: "{{ dotdir.profile }}/pager"
  - editor:
    src: "{{ role_resource.profile }}/editor"
    dest: "{{ dotdir.profile }}/editor"
  - visual:
    src: "{{ role_resource.profile }}/visual"
    dest: "{{ dotdir.profile }}/visual"
  - browser:
    src: "{{ role_resource.profile }}/browser"
    dest: "{{ dotdir.profile }}/browser"
  - terminal:
    src: "{{ role_resource.profile }}/terminal"
    dest: "{{ dotdir.profile }}/terminal"

bashrc_dotfiles:
  - bash_completion:
    src: bash_completion
    dest: "{{ dotdir }}/bash_completion"
  - history:
    src: history_config
    dest: "{{ dotdir }}/history_config"
  - features:
    src: features
    dest: "{{ dotdir }}/features"
  - aliases:
    src: aliases.private
    dest: "{{ dotdir }}/aliases.private"
  - pathlike_utils:
    src: pathlike_utils
    dest: "{{ dotdir }}/pathlike_utils"
  - termcolors_util:
    src: termcolors_util
    dest: "{{ dotdir }}/termcolors_util"
  - archive_utils:
    src: archive_utils
    dest: "{{ dotdir }}/archive_utils"
  - joinby_util:
    src: joinby_util
    dest: "{{ dotdir }}/joinby_util"
  - scaleby_util:
    src: scaleby_util
    dest: "{{ dotdir }}/scaleby_util"
  - jumpcd_util:
    src: jumpcd_util
    dest: "{{ dotdir }}/jumpcd_util"
  - mkpassfile_util:
    src: mkpassfile_util
    dest: "{{ dotdir }}/mkpassfile_util"
  - ps1:
    src: riced_ps1
    dest: "{{ dotdir }}/riced_ps1"
