configs_home: "{{ role_path }}/files"

main_dotfile:
  src: bashrc.private
  dest: ~/.bashrc.private

dotdir: ~/.config/bashrc.d

dotfiles:
  - bash_completion:
    src: bash_completion
    dest: "{{ dotdir }}/05_bash_completion"
  - history:
    src: history_config
    dest: "{{ dotdir }}/05_history_config"
  - features:
    src: features
    dest: "{{ dotdir }}/01_features"
  - aliases:
    src: aliases.private
    dest: "{{ dotdir }}/10_aliases.private"
  - pathlike_utils:
    src: pathlike_utils
    dest: "{{ dotdir }}/25_pathlike_utils"
  - termcolors_util:
    src: termcolors_util
    dest: "{{ dotdir }}/25_termcolors_util"
  - archive_utils:
    src: archive_utils
    dest: "{{ dotdir }}/25_archive_utils"
  - joinby_util:
    src: joinby_util
    dest: "{{ dotdir }}/25_joinby_util"
  - scaleby_util:
    src: scaleby_util
    dest: "{{ dotdir }}/25_scaleby_util"
  - jumpcd_util:
    src: jumpcd_util
    dest: "{{ dotdir }}/25_jumpcd_util"
  - mkpassfile_util:
    src: mkpassfile_util
    dest: "{{ dotdir }}/25_mkpassfile_util"
  - ps1:
    src: riced_ps1
    dest: "{{ dotdir }}/99_riced_ps1"
