configs_home: "{{ role_path }}/files"

main_dotfile:
  src: bashrc.private
  dest: ~/.bashrc.private

dotdir: ~/.config/bashrc.d

dotfiles:
  - bash_completion:
    src: bash_completion
    dest: "{{ dotdir }}/10_bash_completion"
  - history:
    src: history_config
    dest: "{{ dotdir }}/01_history_config"
  - features:
    src: features
    dest: "{{ dotdir }}/02_features"
  - aliases:
    src: aliases.private
    dest: "{{ dotdir }}/20_aliases.private"
  - utils:
    src: utils
    dest: "{{ dotdir }}/21_utils"
