configs_home: "{{ role_path }}/files"

main_dotfile:
  src: bashrc.private
  dest: ~/.bashrc.private

dotdir: ~/.config/bashrc.d

bash_completion:
  src: bash_completion
  dest: "{{ dotdir }}/bash_completion"
