configs_home: "{{ role_path }}/files"

main_dotfile:
  src: bashrc.private
  dest: ~/.bashrc.private

dotdir: ~/.config/bashrc.d

dotfiles:
  - bash_completion:
    src: bash_completion
    dest: "{{ dotdir }}/bash_completion"
  - history:
    src: history_config
    dest: "{{ dotdir }}/history_config"
  - features:
    src: features
    dest: "{{ dotdir }}/features"
