- name: "Preserve dotfiles marked should_backup"
  ansible.builtin.include_role:
    name: backup
  vars:
    backup_target: "{{ item.dest }}"
  loop: "{{ dotfiles_handler_target | selectattr('should_backup') }}"
  loop_control:
    label: "{{ item.dest }}"

- name: "Handle dotfiles of kind template"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
    follow: false
    mode: '751'
  loop: "{{ dotfiles_handler_target | selectattr('kind', 'match', 'template') }}"
  loop_control:
    label: "{{ item.dest }}"

- name: "Handle dotfiles of kind file"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
    follow: false
    mode: '751'
  loop: "{{ dotfiles_handler_target | selectattr('kind', 'match', 'file') }}"
  loop_control:
    label: "{{ item.dest }}"

- name: "Handle dotfiles of kind link"
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
    follow: false
  loop: "{{ dotfiles_handler_target | selectattr('kind', 'match', 'link') }}"
  loop_control:
    label: "{{ item.dest }}"
