#!/usr/bin/env bash

{{ version_control_warn.hashsymb }}

DEVNAME="{{ touchpad_xinput_devname_pad }}"

get_state() {
    local devname="$1"
    xinput list-props "$devname" \
        | grep "Device Enabled" \
        | grep -o "[01]$"
}

apply_state() {
    local -r action="$1"
    local -r devname="$2"
    local -r notify="$3"

    xinput "$action" "$devname" && $notify "$action touchapd $devname"
}

change_state() {
    local -r devname="$1"
    local -r state=$(get_state "$devname")

    case $state in
        0) apply_state enable "$devname" notify-send ;;
        1) apply_state disable "$devname" notify-send ;;
        *) notify-send "Touchapd $devname state change failed";;
    esac
}

change_state "$DEVNAME"
