- name: "ensure destination path {{ item.dest }} exists"
  tags: [setup, git-setup]
  include_role:
    name: mkparents
  vars:
    target: "{{ item.dest }}"
  loop: "{{ aliases }}"
  loop_control:
    label: "{{ item.dest }}"

- name: symlink aliases
  tags: [setup, git-setup]
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
    follow: false
  loop: "{{ aliases }}"
  loop_control:
    label: "{{ item.dest }}"
