- name: "Symlink aliases per shell type"
  tags: [setup, git-setup]
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
    follow: false
  loop: "{{ git_aliases }}"
  loop_control:
    label: "{{ item.dest }} "
