- name: symlink aliases
  tags: [setup, git-setup]
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
    follow: false
  loop: "{{ aliases }}"
  loop_control:
    label: "{{ item.dest }}"
