- name: "ensure not overwriting existing {{ gitconfig.dest }}"
  tags: [setup, git-setup]
  include_role:
    name: backup
  vars:
    target: "{{ gitconfig.dest }}"

- name: "symlink {{ gitconfig.dest }}"
  tags: [setup, git-setup]
  file:
    src: "{{ gitconfig.src }}"
    dest: "{{ gitconfig.dest }}"
    state: link
    force: true
    follow: false
