- name: Install latest package
  tags: [packages, git-packages]
  ansible.builtin.package:
    state: present
    name: git
  become: true

- name: Ensure dotdirs exist
  tags: [setup, git-setup]
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
    mode: '751'
  loop: "{{ git_dotdir | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Setup
  block:
    - name: Gitconfig
      ansible.builtin.import_tasks: gitconfig.yml
    - name: Gitattributes
      ansible.builtin.import_tasks: gitattributes.yml
    - name: Terminal env variable
      ansible.builtin.import_tasks: aliases.yml
