- name: install latest package
  tags: [packages, git-packages]
  package:
    state: latest
    name: git
  become: true

- block:
  - import_tasks: gitconfig.yml
  - import_tasks: gitattributes.yml
  - import_tasks: aliases.yml
