- name: "ensure not overwriting existing {{ main_dotfile.dest }}"
  tags: [setup, git-setup]
  include_role:
    name: backup
  vars:
    target: "{{ main_dotfile.dest }}"

- name: "symlink {{ main_dotfile.dest }}"
  tags: [setup, git-setup]
  file:
    src: "{{ main_dotfile.src }}"
    dest: "{{ main_dotfile.dest }}"
    state: link
    force: true
    follow: false
