- name: Setup pop cosmic
  ansible.builtin.shell:
    cmd: |
      gsettings set org.gnome.shell.extensions.pop-cosmic overlay-key-action WORKSPACES
      gsettings set org.gnome.shell.extensions.pop-cosmic show-workspaces-button true
      gsettings set org.gnome.shell.extensions.pop-cosmic show-applications-button true
      gsettings set org.gnome.shell.extensions.pop-cosmic workspace-picker-left true

- name: Show only close button on titile bar
  ansible.builtin.command:
    cmd: gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:close'

- name: Set gtk theme mode
  ansible.builtin.command:
    cmd: gsettings set org.gnome.desktop.interface gtk-theme 'Pop-dark'

- name: Setup dock
  ansible.builtin.shell:
    cmd: |
      gsettings set org.gnome.shell.extensions.dash-to-dock manualhide false
      gsettings set org.gnome.shell.extensions.dash-to-dock extend-height true
      gsettings set org.gnome.shell.extensions.dash-to-dock show-mounts true
      gsettings set org.gnome.shell.extensions.dash-to-dock click-action cycle-windows
      gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false
      gsettings set org.gnome.shell.extensions.dash-to-dock intellihide true
      gsettings set org.gnome.shell.extensions.dash-to-dock multi-monitor false
      gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 36
      gsettings set org.gnome.shell.extensions.dash-to-dock dock-position BOTTOM
      gsettings set org.gnome.shell.extensions.dash-to-dock dock-alignment CENTER

- name: Setup workspaces
  ansible.builtin.shell:
    cmd: |
      gsettings set org.gnome.mutter dynamic-workspaces true
      gsettings set org.gnome.mutter workspaces-only-on-primary false

- name: Setup fonts
  ansible.builtin.shell:
    cmd: |
      gsettings set org.gnome.desktop.interface font-name 'Ubuntu Medium 10'
      gsettings set org.gnome.desktop.interface document-font-name 'Ubuntu 10'
      gsettings set org.gnome.desktop.interface monospace-font-name 'Ubuntu Mono 10'
      gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Ubuntu Bold 10'
      gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'

- name: Night light
  ansible.builtin.shell:
    cmd: |
      gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
      gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-automatic false
      gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-from 21.0
      gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-to 7.0
      gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 3700
