- name: Get the latest Neovim release information
  ansible.builtin.uri:
    url: https://api.github.com/repos/neovim/neovim/releases/latest
    return_content: true
    body_format: json
  register: release_info

- name: Set the download URL for the AppImage
  ansible.builtin.set_fact:
    appimage_url: "{{ release_info.json.assets | selectattr('name', 'match', 'nvim.appimage') | map(attribute='browser_download_url') | first }}"

- name: Extract the version number from the release tag
  ansible.builtin.set_fact:
    nvim_version: "{{ release_info.json.tag_name }}"

- name: Construct the filename with the version number
  ansible.builtin.set_fact:
    appimage_filename: "nvim-{{ nvim_version }}.appimage"

- name: Download the Neovim AppImage
  ansible.builtin.get_url:
    url: "{{ appimage_url }}"
    dest: "{{ dpdir.bin }}/{{ appimage_filename }}"
    mode: '0755'

- name: Make nvim point to the latest appimage
  ansible.builtin.file:
    src: "{{ dpdir.bin }}/{{ appimage_filename }}"
    dest: "{{ dpdir.bin }}/nvim"
    state: link
    force: yes

- name: Download NVM setup scritp
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh'
    dest: '/tmp/nvm_setup.sh'
    mode: '0755'

- name: Run NVM setup
  ansible.builtin.command: 'bash /tmp/nvm_setup.sh'

- name: Install nodejs
  ansible.builtin.shell: ". {{ lookup('env', 'HOME') }}/.nvm/nvm.sh && nvm install 18"

- name: Clean up NodeSource setup script
  ansible.builtin.file:
    path: '/tmp/nvm_setup.sh'
    state: absent

- name: Install dependencies
  ansible.builtin.package:
    name:
      - python3-pip
      - python3-venv
      - python3-autopep8
      - python3-isort
      - shfmt
      - luarocks
      - perl
      - ripgrep
    state: present
  become: true
