git_resource:
  gitconfig: "{{ git_files }}"
  gitattributes: "{{ git_files }}"
  aliases: "{{ git_files }}/aliases"

git_dotdir:
  config: "~"
  bash_aliases: "{{ dphome }}/bashrc"

git_dotfiles:
  - name: gitconfig
    kind: link
    should_backup: true
    src: "{{ git_resource.gitconfig }}/gitconfig"
    dest: "{{ git_dotdir.config }}/.gitconfig"

  - name: gitattributes
    kind: link
    should_backup: true
    src: "{{ git_resource.gitattributes }}/gitattributes"
    dest: "{{ git_dotdir.config }}/.gitattributes"

  - name: bash aliases
    kind: file
    should_backup: false
    src: "{{ git_resource.aliases }}/aliases.sh"
    dest: "{{ git_dotdir.bash_aliases }}/git.aliases"
