- name: "Check for existing {{ backup_target }}"
  ansible.builtin.stat:
    path: "{{ backup_target }}"
  register: check_result

- name: "Backup when exists {{ backup_target }}"
  ansible.builtin.copy:
    src: "{{ backup_target }}"
    dest: "{{ backup_target }}.{{ bksuffix }}"
    follow: true
    mode: '751'
  when: check_result.stat.exists
