- name: install i3 window manager
  tags: [packages, i3wm-packages]
  package:
    state: latest
    name: i3-wm
  become: true

- block:
  - import_tasks: packages.yml
  - import_tasks: i3config.yml
  - import_tasks: locker.yml
