import = [
    "~/.config/alacritty-themes/themes/monokai_pro.toml"
]

[font]
normal = { family = 'DejaVu Sans Mono', style='Regular'}
size = 12
offset = { x=0, y=0 }

[keyboard]
bindings = [
    { key = "Return", mods = "Super|Shift", action = "SpawnNewInstance"}
]
