import = [
    "~/.config/alacritty-themes/themes/monokai_pro.toml"
]

[font]
normal = { family = 'DejaVu Sans Mono', style='Regular'}
# font size varies, e.g. 12 is too big for Artix i3, but fine for Manjaro i3
# alacritty does not support reading envrionment variables
# to comply with version control make an entry with EOL commment gitignore
# it is predefined attribtue in my git config filtering those lines
# effectivly leaving them off the version controll
# size = 12
offset = { x=0, y=0 }

[keyboard]
bindings = [
    { key = "Return", mods = "Super|Shift", action = "SpawnNewInstance"}
]
