sshome_resource:
  config: "{{ sshome_templates }}"

sshome_dotdir:
  config: "~/.ssh"

sshome_config:
  src: "{{ sshome_resource.config }}/config.j2"
  dest: "{{ sshome_dotdir.config }}/config.template"
