- name: Remove Keybindings
  ansible.builtin.shell:
    cmd: |
      gsettings set org.gnome.settings-daemon.plugins.media-keys home '[]'
      gsettings set org.gnome.settings-daemon.plugins.media-keys email '[]'
      gsettings set org.gnome.settings-daemon.plugins.media-keys help '[]'
      gsettings set org.gnome.settings-daemon.plugins.media-keys www '[]'
      gsettings set org.gnome.shell.extensions.pop-shell tile-enter '[]'

- name: Terminal
  ansible.builtin.shell:
    cmd: |
      gsettings set org.gnome.settings-daemon.plugins.media-keys terminal '[]'
      gsettings set org.gnome.settings-daemon.plugins.media-keys terminal "['<Super>Return']"

- name: Navigate applications and windows and workspaces
  ansible.builtin.shell:
    cmd: |
      gsettings set org.gnome.shell.extensions.pop-shell activate-launcher "['<Super>d']"
      gsettings set org.gnome.shell.extensions.pop-shell focus-down "['<Super>j']"
      gsettings set org.gnome.shell.extensions.pop-shell focus-left "['<Super>h']"
      gsettings set org.gnome.shell.extensions.pop-shell focus-right "['<Super>l']"
      gsettings set org.gnome.shell.extensions.pop-shell focus-up "['<Super>k']"
      gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['<Super>p']"
      gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['<Super>n']"
      gsettings set org.gnome.shell.extensions.pop-shell pop-workspace-up "['<Super><Shift>p']"
      gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-up "['<Super><Shift>p']"
      gsettings set org.gnome.shell.extensions.pop-shell pop-workspace-down "['<Super><Shift>n']"
      gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-down "['<Super><Shift>n']"
      gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-last "['<Super><Shift>0']"
      gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1 "['<Super><Shift>1']"
      gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2 "['<Super><Shift>2']"
      gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3 "['<Super><Shift>3']"
      gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4 "['<Super><Shift>4']"
      gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-last "['<Super>0']"
      gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>1']"
      gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Super>2']"
      gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Super>3']"
      gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Super>4']"
      gsettings set org.gnome.desktop.wm.keybindings switch-applications "['<Super><Tab>']"
      gsettings set org.gnome.settings-daemon.plugins.media-keys logout "['<Super><Shift>Delete']"
      gsettings set org.gnome.shell.extensions.pop-shell toggle-stacking-global "[]"
      gsettings set org.gnome.desktop.wm.keybindings switch-input-source "[]"
      gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "[]"
      gsettings set org.gnome.desktop.wm.keybindings close "['<Super><Shift>q']"
      gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "['<Super><Shift>f']"
      gsettings set org.gnome.desktop.wm.keybindings toggle-maximized "['<Super>f']"

- name: Navigate applications and windows and workspaces
  ansible.builtin.shell:
    cmd: |
      gsettings set org.gnome.shell.keybindings toggle-application-view "[]"
      gsettings set org.gnome.shell.keybindings toggle-message-tray "['<Super>Home']"

- name: Left right tilling by removing fuplicates manually
  ansible.builtin.shell:
    cmd: |
      gsettings set org.gnome.shell.extensions.pop-shell pop-monitor-left "[]"
      gsettings set org.gnome.mutter.keybindings toggle-tiled-left "['<Super><Shift>h']"
      gsettings set org.gnome.shell.extensions.pop-shell pop-monitor-right "[]"
      gsettings set org.gnome.mutter.keybindings toggle-tiled-right "['<Super><Shift>l']"
