- name: Download the latest Neovim AppImage into "{{ dpdir.bin }}"
  ansible.builtin.import_tasks:
    file: nvim.yml

- name: Desktop setup
  ansible.builtin.import_tasks:
    file: desktop.yml

- name: Screen setup
  ansible.builtin.import_tasks:
    file: screen.yml

- name: Power setup
  ansible.builtin.import_tasks:
    file: power.yml

- name: Mouse setup
  ansible.builtin.import_tasks:
    file: mouse.yml
