#!/usr/bin/env bash

{{ version_control_warn.hashsymb }}

GAMMA_CORRECTION_SERVICE=gammastep

if ! pidof -qx $GAMMA_CORRECTION_SERVICE; then
    $GAMMA_CORRECTION_SERVICE &
    notify-send "Started gamma corection service: $GAMMA_CORRECTION_SERVICE"
fi
