- name: "Preserve existing {{ alacritty_config.dest }}"
  tags: [setup, alacritty-setup]
  ansible.builtin.include_role:
    name: backup
  vars:
    backup_target: "{{ alacritty_config.dest }}"

- name: "Symlink towards {{ alacritty_config.dest }}"
  tags: [setup, alacritty-setup]
  ansible.builtin.file:
    src: "{{ alacritty_config.src }}"
    dest: "{{ alacritty_config.dest }}"
    state: link
    force: true
    follow: false
