- name: "Sub | Preserve existing {{ alacritty_config.dest }}"
  tags: [setup, alacritty-setup]
  ansible.builtin.include_role:
    name: backup
  vars:
    backup_target: "{{ alacritty_config.dest }}"

- name: "Sub | Symlink towards {{ alacritty_config.dest }}"
  tags: [setup, alacritty-setup]
  ansible.builtin.template:
    src: "{{ alacritty_config.src }}"
    dest: "{{ alacritty_config.dest }}"
    force: true
    follow: false
    mode: "751"
