- name: check for existing dotdir
  tags: [setup, alacritty-setup]
  stat: path="{{ dotdir }}"
  register: check_result

- name: backup existing dotdir
  tags: [setup, alacritty-setup]
  copy:
    src: "{{ dotdir }}"
    dest: "{{ dotdir }}.{{ bksuffix }}"
    follow: true
  when: check_result.stat.exists

- name: create new dotdir
  tags: [setup, alacritty-setup]
  file:
    path: "{{ dotdir }}"
    state: directory
