- name: Install latest package
  tags: [packages, alacritty-packages]
  ansible.builtin.package:
    state: present
    name: alacritty
  become: true

- name: Setup
  block:
    - name: Config
      ansible.builtin.import_tasks: config.yml
    - name: Themes
      ansible.builtin.import_tasks: themes.yml
    - name: Terminal env variable
      ansible.builtin.import_tasks: terminal.yml
