- name: "symlink {{ main_dotfile.dest }}"
  tags: [setup, alacritty-setup]
  file:
    src: "{{ configs_home }}/{{ main_dotfile.src }}"
    dest: "{{ main_dotfile.dest }}"
    state: link
    force: true
    follow: false
