- name: install latest package
  tags: [packages, alacritty-packages]
  package:
    state: latest
    name: alacritty

- block:
  - import_tasks: configuration.yml
  - import_tasks: themes.yml
  - import_tasks: terminal.yml
