- name: install latest package
  tags: [packages, alacritty-packages]
  package:
    state: latest
    name: alacritty

- block:
  - import_tasks: dotdir.yml
  - import_tasks: main_dotfile.yml

- name: get themes
  tags: [packages, alacritty-packages]
  git:
    repo: https://github.com/alacritty/alacritty-theme.git
    dest: "{{ dotdir }}/../alacritty-themes"
    depth: 1
  ignore_errors: true
