- name: "ensure not overwriting existing {{ main_dotfile.dest }}"
  tags: [setup, alacritty-setup]
  include_role:
    name: backup
  vars:
    target: "{{ main_dotfile.dest }}"

- name: "ensure destination path {{ main_dotfile.dest | dirname }} exists"
  tags: [setup, alacritty-setup]
  file:
    path: "{{ main_dotfile.dest | dirname }}"
    state: directory

- name: "symlink {{ main_dotfile.dest }}"
  tags: [setup, alacritty-setup]
  file:
    src: "{{ main_dotfile.src }}"
    dest: "{{ main_dotfile.dest }}"
    state: link
    force: true
    follow: false
