alacritty_files: "{{ role_path }}/files"
alacritty_templates: "{{ role_path }}/templates"

alacritty_resource:
  config_templates: "{{ alacritty_templates }}/config"
  terminal: "{{ alacritty_files }}/terminal"

alacritty_dotdir:
  config: "~/.config/alacritty"
  terminal: "{{ dphome }}/profile"

alacritty_config:
  src: "{{ alacritty_resource.config_templates }}/alacritty.toml.j2"
  dest: "{{ alacritty_dotdir.config }}/alacritty.toml"

alacritty_terminal:
  src: "{{ alacritty_resource.terminal }}/terminal"
  dest: "{{ alacritty_dotdir.terminal }}/terminal"
