#!/usr/bin/env bash

{{ version_control_warn.hashsymb }}

TMPFILE=/tmp/lockbg_XXXXXX.png
BGEFFECT=pixelate

make_screenshot() {
    import -silent -window root "$1"
}

pixelate() {
    # BGEFFECT
    magick "$1" -scale 10% -scale 1000% "$1"
}

blur() {
    # BGEFFECT
    magic "$1" -blur 2,5 "$1"
}

screenshot=$(mktemp "$TMPFILE")

make_screenshot $screenshot

$BGEFFECT $screenshot

i3lock --show-failed-attempts --nofork --image $screenshot

trap 'rm -f $background' EXIT
