#!/usr/bin/env bash

{{ version_control_warn.hashsymb }}

NOTIFICATION_ID=${XDG_RUNTIME_DIR:-~/.local/share}/volume.id

get_volume() {
    local volume=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '\d+\%' | sort -u)
    echo "${volume%\%}"
}

get_notification_id() {
    [[ ! -f $NOTIFICATION_ID ]] && echo $RANDOM > $NOTIFICATION_ID
    cat $NOTIFICATION_ID
}

main() {
    local -r action=${1:-toggle}

    pactl set-sink-mute @DEFAULT_SINK@ $action

    local -r notification_id=$(get_notification_id)
    local -r sink_mute_status=$(pactl get-sink-mute @DEFAULT_SINK@)

    local volume=0

    [[ "$sink_mute_status" == 'Mute: no' ]] && volume=$(get_volume)

    notify-send -r $notification_id "Volume $sink_mute_status" -h int:value:$volume -h string:synchronous:volume
}

main "$@"
