- name: Set up the role resources facts
  tags: [setup, nvim-setup]
  ansible.builtin.set_fact:
    nvim_files: "{{ role_path }}/files"
    nvim_templates: "{{ role_path }}/templates }}"

- name: Install latest package
  tags: [packages, nvim-packages]
  ansible.builtin.package:
    state: present
    name: neovim
  become: true

- name: Ensure dotdirs exist
  tags: [setup, nvim-setup]
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
    mode: '751'
  loop: "{{ nvim_dotdir | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: "Handle nvim dotfiles"
  tags: [setup, nvim-setup]
  ansible.builtin.import_role:
    name: dotfiles_handler
  vars:
    dotfiles_handler_target: "{{ nvim_dotfiles }}"

- name: "Handle nvim plugins dotfiles"
  tags: [setup, nvim-setup]
  ansible.builtin.import_role:
    name: dotfiles_handler
  vars:
    dotfiles_handler_target: "{{ nvim_plugins_dotfiles }}"
