- name: install clipboard provider
  tags: [packages, nvim-packages]
  package:
    state: latest
    name: xsel
  become: true

- name: "create {{ dotdir.nvim }}"
  tags: [setup, nvim-setup]
  file:
    path: "{{ dotdir.nvim }}"
    state: directory

- name: "ensure not overwriting existing {{ nvim.dest }}"
  tags: [setup, nvim-setup]
  include_role:
    name: backup
  vars:
    target: "{{ nvim.dest }}"

- name: "symlink {{ nvim.dest }}"
  tags: [setup, nvim-setup]
  file:
    src: "{{ nvim.src }}"
    dest: "{{ nvim.dest }}"
    state: link
    force: true
    follow: false

- name: "create {{ dotdir.lua }}"
  tags: [setup, nvim-setup]
  file:
    path: "{{ dotdir.lua }}"
    state: directory

- name: "create {{ dotdir.plugins }}"
  tags: [setup, nvim-setup]
  file:
    path: "{{ dotdir.plugins }}"
    state: directory

- name: "create plugins setup stub"
  tags: [setup, nvim-setup]
  file:
    path: "{{ plugins_setup.dest }}"
    state: touch
