- name: Set up the role resource facts
  tags: [setup, i3wm-setup]
  ansible.builtin.set_fact:
    i3wm_files: "{{ role_path }}/files"
    i3wm_templates: "{{ role_path }}/templates"

- name: Install i3 window manager
  tags: [packages, i3wm-packages]
  ansible.builtin.package:
    state: present
    name: i3-wm
  become: true

- name: Ensure dotdirs exist
  tags: [setup, i3wm-setup]
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
    mode: '751'
  loop: "{{ i3wm_dotdir | dict2items }}"
  loop_control:
    label: "{{ item.value }}"

- name: Set up configuration file
  ansible.builtin.import_tasks:
    file: config.yml

- name: Set up locker utility
  ansible.builtin.import_tasks:
    file: locker.yml

- name: Set up volume control utility
  ansible.builtin.import_tasks:
    file: volumectl.yml

- name: Set up brightness control utility
  ansible.builtin.import_tasks:
    file: brightnessctl.yml

- name: Set up status bar
  ansible.builtin.import_tasks:
    file: statusbar.yml
